### PR TITLE
Improve Debian Releases File

### PR DESCRIPTION
**Pull request by marcohald**
### Description
Added Description to aptly repo create
Added  Label and Origin to aply publish snapshot

### Issues Resolved
Closes  https://github.com/opensearch-project/opensearch-build/issues/4485

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peterzhuamazon — CHANGES_REQUESTED** [review]
Hi @marcohald ,

This file is used for both OS and OSD so we cannot hardcode with comments/labels.

Is there any particular benefits of adding them especially when the repo is created with ${jobname} and snapshot with ${jobname}-${repoVersion} already?

Thanks.

**Comment by marcohald** [comment]
@peterzhuamazon The actual generated File https://artifacts.opensearch.org/releases/bundle/opensearch/2.x/apt/dists/stable/InRelease looks like this at the moment
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Origin: . stable
Label: . stable
Suite: stable
Codename: stable
Date: Tue, 14 May 2024 19:07:45 UTC
Architectures: amd64 arm64
Components: main
Description: Generated by aptly

```
As far as I can see neither ${jobname} or ${repoVersion} is part of that File.
The Problem with that is that it is not as easy to Pin when we cache the Repository with approx.
I could use origin (the hostname of the repo, not the Origin from the Release File) as pin parameter.
The Pinning is to control the Version opensearch that is installed.
In theory there could be multiple Repos on the approx with the same origin that could contain a opensearch package.

As far as i understand the only option that is not from the Release File is the origin to pin.
As found here https://unix.stackexchange.com/a/84812 and here https://manpages.debian.org/bookworm/apt/apt_preferences.5.en.html

**Comment by peterzhuamazon** [comment]
Could you change the comment/origin/label to use different value based on ${jobname} then?
I am happy to have a comment or origin or even label but we shall not hardcode it as this script is used for both OS and OSD and possibly more later on.

Let me know. Thanks.

**Comment by marcohald** [comment]
Thank you for the hint with the different products I didn't thought about that.
I changed it to `${filename}` which should result to "opensearch-dashboards" like the Product: here https://build.ci.opensearch.org/job/distribution-promote-repos/113/console
and "opensearch" for https://build.ci.opensearch.org/job/distribution-promote-repos/111/console
I think the origin could be left hardcoded to opensearch.org what do you think about that?

**Comment by peterzhuamazon** [comment]
I will update your test cases once you commit the requested changes.

Thanks.

**Comment by marcohald** [comment]
Hi @peterzhuamazon 
Sure, thank you for your help with this PR

**Comment by peterzhuamazon** [comment]
Will add test cases in a min.

**Review by peterzhuamazon — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
Thanks @marcohald for the contribution and we should be able to see this change take effect in the next release.

**Comment by peterzhuamazon** [comment]
Waiting for https://github.com/opensearch-project/opensearch-build-libraries/pull/427 to bump verision before update the jenkinsfile.

**Comment by peterzhuamazon** [comment]
Use new lib:
* https://github.com/opensearch-project/opensearch-build/pull/4724

**Pull request merged**
