### PR TITLE
Add standard release pipeline library

### PR DESCRIPTION
**Pull request by gaiksaya**
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>

### Description
Add standard release pipeline library

### Issues Resolved
resolves https://github.com/opensearch-project/opensearch-build/issues/1606

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by gaiksaya** [comment]
Tests are failing. I am missing something for sure:

```
TestStandardReleasePipeline > testStandardReleasePipeline FAILED
    groovy.lang.MissingPropertyException: Exception evaluating property 'overrideDockerImage' for java.util.Arrays$ArrayList, Reason: groovy.lang.MissingPropertyException: No such property: overrideDockerImage for class: StandardReleasePipeline_JenkinsFile
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.getAtIterable(DefaultGroovyMethods.java:8761)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.getAt(DefaultGroovyMethods.java:8749)
        at groovy.lang.MetaClassImpl$7.getProperty(MetaClassImpl.java:2082)
        at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:63)
```

**Comment by prudhvigodithi** [comment]
Hey @gaiksaya i see the issue is the created lib-tester `StandardReleasePipelineLibTester`, which does not consider args as class variables.
I have removed the `this.registerLibTester(new StandardReleasePipelineLibTester('AL2-X64', 'test:image'))` and with just `super.setUp()` in `TestStandardReleasePipeline.grrovy`, the tests pass.

Output
I can see the `overrideAgent` and `overrideDockerImage` are passed right.
```
TestStandardReleasePipeline > testStandardReleasePipeline STANDARD_OUT
    Loading shared library jenkins with version <notNeeded>
    Executing on agent [docker:[image:test:image, reuseNode:false, stages:[:], args:, alwaysPull:true, containerPerStageRoot:false, label:AL2-X64]]
    fakePublishToMaven [mavenArtifactsPath:/maven, autoPublish:true]
       StandardReleasePipeline_JenkinsFile.run()
          StandardReleasePipeline_JenkinsFile.standardReleasePipeline({overrideAgent=AL2-X64, overrideDockerImage=test:image}, groovy.lang.Closure)
             standardReleasePipeline.pipeline(groovy.lang.Closure)
                standardReleasePipeline.timeout({time=1, unit=HOURS})
                standardReleasePipeline.echo(Executing on agent [docker:[image:test:image, reuseNode:false, stages:[:], args:, alwaysPull:true, containerPerStageRoot:false, label:AL2-X64]])
                standardReleasePipeline.stage(Release, groovy.lang.Closure)
                   standardReleasePipeline.script(groovy.lang.Closure)
                      StandardReleasePipeline_JenkinsFile.echo(fakePublishToMaven [mavenArtifactsPath:/maven, autoPublish:true])
                standardReleasePipeline.script(groovy.lang.Closure)
                   standardReleasePipeline.postCleanup()
                      postCleanup.cleanWs({disableDeferredWipeout=true, deleteDirs=true})
                   standardReleasePipeline.sh(docker image prune -f --all)
```

**Comment by gaiksaya** [comment]
Thanks @prudhvigodithi , I added few more tests and removed the Libtester. Don't think it's required.

**Comment by prudhvigodithi** [comment]
Hey @gaiksaya is it worth to add a README on how to use the `vars/standardReleasePipeline.groovy` file? an example in the readme?

**Comment by gaiksaya** [comment]
> Hey @gaiksaya is it worth to add a README on how to use the `vars/standardReleasePipeline.groovy` file? an example in the readme?

Thanks for reminding @prudhvigodithi . Added the details to the readme.

**Review by prudhvigodithi — APPROVED** [review]

**Pull request merged**
